// 界面文案集中放这里，方便统一修改 / 换语言。
export const t = {
  search: "搜索",
  searchPlaceholder: "按关键字搜索",
  allStatuses: "全部状态",
  newRecord: "新增记录",
  signOut: "退出",
  updatedAt: "更新于",
  save: "保存",
  saving: "保存中…",
  cancel: "取消",
  delete: "删除",
  deleteConfirm: "确定删除这条记录？此操作无法撤销。",
  edit: "编辑",
  close: "关闭",
  required: "必填",
  emptyTitle: "还没有任何记录",
  emptyBody: "点右上角「新增记录」添加第一条，或在 Claude Code 里让 AI 帮你导入示例数据。",
  loadError: "加载失败",
  saveError: "保存失败",
  deleteError: "删除失败",
  retry: "重试",
  recordCount: (n: number) => `共 ${n} 条`,
  newRecordTitle: "新增记录",
  lockedTitle: "需要访问权限",
  lockedBody: "这是一个受保护的内部页面。请使用带访问密码的链接打开。",
  lockedHint: "链接形如：https://你的网址/?key=访问密码",
};
